import type { Tables, TablesInsert, TablesUpdate, Enums } from "./db/database.types";

// ============================================================================
// Base Entity DTOs (directly mapped from database tables)
// ============================================================================

/**
 * Flashcard entity - represents a single flashcard with spaced repetition data
 */
export type FlashcardDTO = Tables<"flashcards">;

/**
 * Generation log entity - tracks user interactions with AI-generated flashcards
 */
export type GenerationLogDTO = Tables<"generation_logs">;

/**
 * Generation error log entity - tracks errors during AI flashcard generation
 */
export type GenerationErrorLogDTO = Tables<"generation_error_logs">;

/**
 * User entity - represents a user profile
 */
export type UserDTO = Tables<"users">;

/**
 * Generation status enum - tracks how user interacted with AI-generated candidate
 */
export type GenerationStatus = Enums<"generation_status">;

// ============================================================================
// Flashcard Generation DTOs (POST /api/flashcards/generate)
// ============================================================================

/**
 * Request body for generating flashcard candidates from source text
 * Validation: source_text must be 1000-10000 characters
 */
export interface GenerateFlashcardsRequestDTO {
  source_text: string;
}

/**
 * Flashcard candidate generated by AI (not yet persisted to database)
 * Validation: front ≤ 200 chars, back ≤ 500 chars
 */
export interface FlashcardCandidateDTO {
  front: string;
  back: string;
}

/**
 * Response containing AI-generated flashcard candidates
 */
export interface GenerateFlashcardsResponseDTO {
  candidates: FlashcardCandidateDTO[];
}

// ============================================================================
// Flashcard CRUD DTOs
// ============================================================================

/**
 * Metadata for tracking AI-generated flashcard acceptance/editing
 * Used when creating a flashcard from an AI-generated candidate
 */
export interface GenerationMetadataDTO {
  original_front: string;
  original_back: string;
}

/**
 * Request body for creating a new flashcard
 * Can be used for manual creation or accepting/editing AI-generated candidates
 *
 * If generation_metadata is provided:
 * - System compares front/back with original_front/original_back
 * - Creates generation_log entry with appropriate status
 *
 * Validation: front ≤ 200 chars, back ≤ 500 chars
 */
export interface CreateFlashcardRequestDTO {
  front: string;
  back: string;
  generation_metadata?: GenerationMetadataDTO;
}

/**
 * Request body for updating an existing flashcard
 * Only front and back content can be updated
 * Validation: front ≤ 200 chars, back ≤ 500 chars
 */
export type UpdateFlashcardRequestDTO = Pick<TablesUpdate<"flashcards">, "front" | "back">;

/**
 * Query parameters for listing flashcards
 * Supports pagination and search filtering
 */
export interface ListFlashcardsQueryDTO {
  page?: number; // Page number (≥ 1), default: 1
  limit?: number; // Items per page (1-100), default: 20
  search?: string; // Search query to filter by front or back content
}

/**
 * Pagination metadata for list responses
 */
export interface PaginationMetadataDTO {
  page: number; // Current page number
  limit: number; // Items per page
  total: number; // Total number of items
  pages: number; // Total number of pages
}

/**
 * Response for listing flashcards with pagination
 */
export interface ListFlashcardsResponseDTO {
  data: FlashcardDTO[];
  pagination: PaginationMetadataDTO;
}

// ============================================================================
// Generation Logs DTOs (POST /api/generation-logs)
// ============================================================================

/**
 * Request body for creating a generation log entry (rejecting a candidate)
 * Used when user rejects an AI-generated candidate without creating a flashcard
 *
 * Note: Logs for 'accepted' and 'accepted_with_edit' are created automatically
 * by POST /api/flashcards when generation_metadata is provided
 */
export interface CreateGenerationLogRequestDTO {
  status: "rejected";
  original_front: string;
  original_back: string;
}

// ============================================================================
// Study Session DTOs
// ============================================================================

/**
 * Query parameters for getting due flashcards
 */
export interface GetDueFlashcardsQueryDTO {
  limit?: number; // Maximum number of flashcards to return (1-100), default: 20
}

/**
 * Response containing flashcards due for review
 */
export interface DueFlashcardsResponseDTO {
  data: FlashcardDTO[];
  total_due: number; // Total number of flashcards due (without limit)
}

/**
 * Review rating scale for spaced repetition algorithm
 * 1 = Again (complete failure)
 * 2 = Hard (difficult but recalled)
 * 3 = Good (recalled with some effort)
 * 4 = Easy (perfect recall)
 */
export type ReviewRating = 1 | 2 | 3 | 4;

/**
 * Request body for submitting a flashcard review
 * Updates flashcard scheduling using FSRS algorithm
 */
export interface SubmitReviewRequestDTO {
  flashcard_id: string;
  rating: ReviewRating;
}

// ============================================================================
// Error Response DTOs
// ============================================================================

/**
 * Standard error response format used across all API endpoints
 */
export interface ApiErrorResponseDTO {
  error: {
    code: string;
    message: string;
    details?: Record<string, any>;
  };
}

/**
 * Error codes used in API responses
 */
export type ApiErrorCode =
  | "VALIDATION_ERROR"
  | "UNAUTHORIZED"
  | "NOT_FOUND"
  | "RATE_LIMIT_EXCEEDED"
  | "AI_GENERATION_FAILED"
  | "AI_TIMEOUT"
  | "INTERNAL_ERROR";

// ============================================================================
// Review History Types (for JSONB field in flashcards table)
// ============================================================================

/**
 * Single review entry in flashcard review history
 * Stored in flashcards.review_history JSONB field
 */
export interface ReviewHistoryEntry {
  date: string; // ISO 8601 timestamp
  rating: ReviewRating;
}

/**
 * Type guard to check if review_history JSONB is valid
 */
export type ReviewHistory = ReviewHistoryEntry[];

// ============================================================================
// OpenRouter Service Types
// ============================================================================

/**
 * Message in a chat completion request
 */
export interface ChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

/**
 * JSON Schema definition for structured responses
 */
export interface JsonSchema {
  type: "object";
  properties: Record<string, unknown>;
  required?: string[];
}

/**
 * Response format configuration for structured JSON responses
 */
export interface ResponseFormat {
  type: "json_schema";
  json_schema: {
    name: string;
    strict?: boolean;
    schema: JsonSchema;
  };
}

/**
 * Options for chat completion requests to OpenRouter API
 */
export interface ChatCompletionOptions {
  model: string;
  messages: ChatMessage[];
  response_format?: ResponseFormat;
  temperature?: number;
  max_tokens?: number;
  top_p?: number;
}
